const MINE_RATE = 3000;

const DIFFICULTY = 3;

const INITIAL_BALANCE = 777;

const MINING_REWARD = 5;

const TRANSACTION_FEES = 1;

module.exports = { MINING_REWARD, INITIAL_BALANCE, DIFFICULTY, MINE_RATE, TRANSACTION_FEES };